### ISSUE TITLE
i18n not properly working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bitsed/qosmic#15]
```
What steps will reproduce the problem?

1. Placed qosmic_ru.ts/qm to ts dir
2. Added qosmic_ru.ts to qosmic.pro
3. Ran ./build.sh
4. UI is still in English

So:

1. What do I do? :)
2. Is qosmic really trying to compile QM into its binary? Why? :)
```

Original issue reported on code.google.com by `alexandr...@gmail.com` on 28 Jul 2009 at 5:55

**Comment by bitsed** [comment]
I ran lupdate with the translation file you attached, and I added it to the repository.  I'm able to load them when the value of TRANSDIR in qosmic.pro is set to the directory containing the .qm files.  They should be installed to this location.  Can you please verify?

**Comment by bitsed** [comment]
I've moved the .qm files into the resources structure.  This should make packaging easier since these files are now bundled in the executable instead of being installed in the file system.  All references to TRANSDIR have been removed.

Should some type of support to read the translations from the file system be kept?

**Comment by bitsed** [comment]
Translations are now included in application resources.
Closing this issue.  Thanks!
